In [38]:
import numpy as np

In [18]:
data  = np.array([1.1,2.2,3.3])

In [19]:
data

array([1.1, 2.2, 3.3])

In [20]:
np.zeros(shape=(3,4),dtype="float32")

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [21]:
np.ones(shape=(2,3),dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1]])

In [23]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
np.arange(0,10,5)

array([0, 5])

In [34]:
data1 = np.random.uniform(low=-1,high=1,size=1000000)

In [35]:
data1

array([ 0.8239176 , -0.42179263, -0.48426223, ...,  0.5321799 ,
       -0.15828227, -0.37829773])